### PR TITLE
Fixed #9 - solved (hopefully) the issue with the scoring being out of whack 

### LINKED ISSUE #9: Scoring may be totally broken...
Sometimes off by 1, sometimes more

### PR DESCRIPTION
**Pull request by belfortk**
(related to bonus guesses). added \n to clean things up in gameflow.

### CODE REVIEW

File: Game.java [hunk 1]
```diff
@@ -43,10 +43,10 @@ public Game() throws FileNotFoundException
    }
 
    public void run() throws InterruptedException {
-      System.out.println("Welcome to Codenames! Please pick your Code Master and have them sit nearest to the computer.");
+      System.out.println("Welcome to Codenames! Please pick your Code Master and have them sit nearest to the computer. \n");
```
Comment (cabelhigh) [inline Game.java:46]: \n works; so does doing another System.out.println(). It's just preference.

File: Game.java [hunk 2]
```diff
@@ -204,7 +224,7 @@ private int turnToInt(String s) {
 
 
    private boolean verifyClue(String clue) {
-      if(clue.contains(" ") || board.isCardOnBoard(clue))
+      if(clue.contains(" ") || board.isCardOnBoard(clue) )
```
Comment (cabelhigh) [inline Game.java:227]: Formatting

File: Game.java [hunk 3]
```diff
@@ -132,20 +143,29 @@ public void run() throws InterruptedException {
...
+                                else if (guessCardTeam == CardTeam.BLUE)
+                                {
                                     blueRemaining--;
                                 }
+                                else if (guessCardTeam == CardTeam.CIVILIAN){
+                                   currentGuesses = -1;
+                                }
+                                else if (guessCardTeam == CardTeam.ASSASSIN){
+                                   currentGuesses=-1;
+                                   victory=true;
```
Comment (cabelhigh) [inline Game.java:155]: Unsure why this is not ending the game; new bug fix!

**Review by cabelhigh — APPROVED** [review]
The scoring now works! The bonus assassin does not :(
